export enum ActionTypes {
  TO_DO_LIST_INITIAL_TASKS = 'TO_DO_LIST_INITIAL_TASKS',
  TO_DO_LIST_ADD_TASK = 'TO_DO_LIST_ADD_TASK',
  TO_DO_LIST_REMOVE_TASK = "TO_DO_LIST_REMOVE_TASK",
  TO_DO_LIST_UPDATE_STATUS_TASK = 'TO_DO_LIST_UPDATE_STATUS_TASK',
}
